databases:
  - name: postgres_messageapp
    plan: free

services:
  - type: web
    plan: free
    name: rails
    runtime: ruby
    buildCommand: './bin/render-build.sh'
    startCommand: 'bundle exec puma -C config/puma.rb'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres_messageapp
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
  - type: redis
    name: redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction
